<MyRoot>:

    testLabel: testLabel

    BoxLayout
        orientation: 'vertical'
        Label:
            text: 'asdfasfasf'
            font_size: 64
            color: 0.92, 0.45, 0
        Label:
            id: testLabel
            text: 'a'
            font_size: 64
        Button:
            text: 'Asdd'
            font_size: 32
            size: 100, 50
            on_press: root.button()